version: '3.8'

services:
  backend:
    image: arrguardian-backend
    build:
      context: ./backend
    environment:
      SONARR_URL: "https://jrcorwin-sonarr.elfhosted.com"
      SONARR4K_URL: "https://jrcorwin-sonarr4k.elfhosted.com"
      RADARR_URL: "https://jrcorwin-radarr.elfhosted.com"
      RADARR4K_URL: "https://jrcorwin-radarr4k.elfhosted.com"
    ports:
      - "8000:8000"

  frontend:
    image: arrguardian-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
